### numpy 라이브러리
- 빅데이터의 수학적 과학적 계산을 위해 만들어진 라이브러리
- 반복문 없이 전체 데이터의 연산이 가능한 표준 수학 함수들을 제공

* 배열: 같은 자료형의 값들이 연속적인 형태로 구성된 자료 구조로 대량의 데이터를 그룹으로 관리하고 계산하기 위해 사용!


In [1]:
# numpy 라이브러리를 불러와서 np로 지칭하겠다!
import numpy as np

In [2]:
list1=[1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [3]:
type(list1)

list

In [5]:
arr= np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

### 1차원 배열

In [8]:
arr=np.array([1,2,3.5])
arr

array([1. , 2. , 3.5])

In [9]:
# array는 자료형이 다 같은 자료형으로 이루어야 한다
#계산을 위해서!
#그러므로 자료형을 바꿔주면 다 같이 바뀐다.


In [11]:
arr=np.array([1,2,"야호"])
arr

array(['1', '2', '야호'], dtype='<U11')

### 2차원 배열

In [12]:
arr2= np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# 배열의 형태 확인 (행과 열)
arr2.shape

(2, 3)

In [14]:
#배열의 요소 전체 개수
arr2.size

6

In [15]:
#배열의 데이터 타입(자료형 확인)
arr2.dtype

dtype('int32')

In [16]:
#32는 bit를 뜻함 (기계가 표현할수 있는 범위 2^32
#int8-> 1비트당 2개의 숫자를 표현할수 있음 2^8=256개 표현 가능
#-128~127
#int32=> -2,147,483,648~ 2,147,483,647

In [17]:
# 배열의 차원 확인 
arr2.ndim

2

In [18]:
#예제
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
arr3.size

8

In [21]:
arr3.dtype

dtype('int32')

In [22]:
arr3.shape

(2, 2, 2)

In [23]:
arr3.ndim

3

#### 배열의 형태 차원. 전체 요소개수를 출력해보세요

In [24]:
print("배열의 형태:",arr3.shape)
print("배열의 차원:",arr3.ndim)
print("배열의 전체 요소 개수:",arr3.size)

배열의 형태: (2, 2, 2)
배열의 차원: 3
배열의 전체 요소 개수: 8


In [27]:
# 0으로 배열 생성

arr_zeros=np.zeros((4,2,3,4))
arr_zeros

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [28]:
#1로 배열 생성
arr_ones=np.ones((2,4,3))
arr_ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [30]:
#특정값으로 배열 생성하기
arr_full=np.full((2,5,5),2)#5행 5열의 배열을 2로 채워준다
arr_full

array([[[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])

#### 다차원 배열 생성에 유용한 함수
 
 * arrange함수로 배열을 생성하고 reshape함수로 배열의 형태를 바꿔보자

In [35]:
#1부터 50까지 1씩 증가하는 값들로 리스트를 만들어 주세요
arr_list=[]
for i in range(1,51):
    arr_list.append(i)
print(arr_list)

np.array(arr_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [37]:
#반복문을 활용하지 않고 배열 생성
arr5=np.arange(1,51,1)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [42]:
arr6=np.arange(1,51,10)
arr6

array([ 1, 11, 21, 31, 41])

11

In [45]:
arr6=np.arange(1,51,10)
arr6

array([ 1, 11, 21, 31, 41])

In [47]:
arr7=np.arange(1,51,1)
arr7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [52]:
# reshape: 배열의 행과 열을 변경시켜주는 명령
arr7.reshape(10,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [53]:
#실수 값을 가지는 배열 생성
arr8=np.array([1.2,2.3,3.4])
arr8

array([1.2, 2.3, 3.4])

In [54]:
#배열의 자료형을 정수형으로 형변환 하여 출력
arr8=np.array([1.2,2.3,3.4], dtype=np.int64)
arr8

array([1, 2, 3], dtype=int64)

In [55]:
arr9= np.array(['1','2','3'], dtype=np.int64)
arr9

array([1, 2, 3], dtype=int64)

In [56]:
arr9= np.array(['안녕','하세요','반갑습니다'], dtype=np.int64)
arr9

ValueError: invalid literal for int() with base 10: '안녕'

#### 랜덤 (난수) 값 생성!

In [60]:
#랜덤한 값으로 배열 생성하기
arr10=np.random.rand(2,3) #6개 (2행 3열)
arr10 #0~1사이

array([[0.70376929, 0.4195125 , 0.29474901],
       [0.42538764, 0.28958181, 0.64877713]])

In [66]:
#랜덤 정수 값 출력하기
arr11=np.random.randint(10)
#0~ 해당 값까지에 랜덤하게 정수를 생성
arr11

3

In [67]:
#랜덤값 정수형 배열 생성하기
np.random.randint(5, size=10)

array([0, 3, 0, 2, 4, 3, 3, 4, 4, 0])

In [68]:
np.random.randint(5, size=(2,3))

array([[3, 2, 1],
       [0, 3, 3]])

### array연산

In [70]:
arr14=np.array([[1,2],[3,4]])
arr14

array([[1, 2],
       [3, 4]])

In [71]:
arr14+arr14

array([[2, 4],
       [6, 8]])

In [72]:
list14=[[1,2],[3,4]]
list14

[[1, 2], [3, 4]]

In [73]:
list14+list14

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [74]:
arr14-arr14

array([[0, 0],
       [0, 0]])

In [75]:
arr14*arr14

array([[ 1,  4],
       [ 9, 16]])

In [76]:
arr14**arr14

array([[  1,   4],
       [ 27, 256]], dtype=int32)

In [77]:
arr14/arr14

array([[1., 1.],
       [1., 1.]])

In [78]:
arr14%arr14

array([[0, 0],
       [0, 0]], dtype=int32)

### numpy 배열의 접근은 어떻게 할까?
* 리스트와 마찬가지로 인덱싱 슬라이싱을 지원함

#### numpy 배열 인덱싱
* 배열중 하나의 인덱스 값에 있는 데이터를 가져오는 것


In [79]:
arr16=np.array([[1,2,3],[4,5,6]])
arr16

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr16[0]

array([1, 2, 3])

In [81]:
arr16[0][1]

2

In [82]:
arr16[1][1]

5

#### numpy 슬라이싱
* 배열의 범위를 지정하여 여러개의 데이터를 가져오는것

In [83]:
arr17=np.arange(10)
arr17

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr17[3:8]

array([3, 4, 5, 6, 7])

In [88]:
arr18=np.arange(50).reshape(5,10)
arr18

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [89]:
#0번, 1번 인덱스 행의 모든 열을 출력(arr18[행의 범위, 열의 범위])
arr18[0:2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [90]:
# 모든 행의 0번 인덱스를 출력
arr18[:,:1]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [91]:
arr18[:,0]

array([ 0, 10, 20, 30, 40])

In [92]:
arr18[:,:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41]])

In [94]:
arr18[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [96]:
arr19=np.arange(18).reshape(3,6)
arr19

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]


In [97]:
#방법
arr19[1:,[1,3,5]]

array([[ 7,  9, 11],
       [13, 15, 17]])

In [98]:
#방법 2
arr19[1:,1: :2]

array([[ 7,  9, 11],
       [13, 15, 17]])

In [100]:
# 전치: 배열의 행과 열을 바꿔주는 것
arr19.T

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])